---
- name: install redis on Server
  hosts: Device
  roles:
    - redis

- name: start redis on server
  hosts: Device
  roles:
    - redis-server

- name: install redis on client
  hosts: TestNode
  roles:
    - redis

