
- hosts: Device
  tasks:
    - name: remove latest data
      file:
        path: /tmp/iperf_output.log
        state: absent

    - name: run iperf3 TCP_sin_10_rx
      with_items:
        - "{{ groups['TestNode'] }}"
      shell: iperf3 -c {{ item }} -f M -i 1 -O 5 -t 100 -P 10 -w 256k -R
      register: logdata
      ignore_errors: yes


    - lineinfile: create=yes dest=/tmp/iperf_output.log line="{{ item }}.stdout" state=present
      with_items:
        - "{{ logdata }}"



    - name: fetch result
      fetch:
        src: /tmp/iperf_output.log
        dest: /tmp/iperf_output.log
        flat: yes
